// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://xtmztlzdvtnkdnozmgwp.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inh0bXp0bHpkdnRua2Rub3ptZ3dwIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTcxNzczNTksImV4cCI6MjA3Mjc1MzM1OX0.KhNggxrHZ6Ym86sWvA1EPJAWzh3uCp18S4tTe_pHJno";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});